version: '2'

services:
#   app:
#     build: ./app
#     networks:
#       - abyss
#     environment:
#       - MONGO_URL=mongodb://mongo:27017/plebiscite
# #    volumes:
# #      - /etc/localtime:/etc/localtime:ro
#     restart: always
#     ulimits:
#       nproc: 65535
#       nofile:
#         soft: 800000
#         hard: 900000

  mongo:
    command: mongod --setParameter failIndexKeyTooLong=false
#    image: mongo:3.7.9
    image: mongo:3.6.4
    networks:
      - abyss
    volumes:
     - ./db/mongo:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    networks:
      - abyss
    volumes:
      - ./db/esdata:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9300
    ports:
      - 9200:9200
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 800000
        hard: 900000

networks:
  abyss:
    ipam:
      driver: default
      config:
        - subnet: 254.253.0.0/16
          ip_range: 254.253.252.0/24
          gateway: 254.253.252.251
